In [1]:
import tensorflow as tf
import tensorflow_datasets as tfds
from transformers import DistilBertTokenizer, TFDistilBertForSequenceClassification
from transformers import *
import numpy as np
from tqdm import tqdm

from attention_graph_util import *
from notebooks.notebook_utils import *
from util import inflect

from tqdm import tqdm
import math
import pandas as pd

import os
os.environ["CUDA_DEVICE_ORDER"]="PCI_BUS_ID"   # see issue #152
os.environ["CUDA_VISIBLE_DEVICES"]="1"

[nltk_data] Downloading package punkt to /home/dehghani/nltk_data...
[nltk_data]   Package punkt is already up-to-date!


In [2]:
tokenizer = DistilBertTokenizer.from_pretrained('distilbert-base-uncased')
model = TFDistilBertForSequenceClassification.from_pretrained('distilbert-base-uncased-finetuned-sst-2-english')

In [3]:
data = tfds.load('glue/sst2')

# Prepare dataset for GLUE as a tf.data.Dataset instance
train_dataset = glue_convert_examples_to_features(data['train'], tokenizer, max_length=128, task='sst-2')
valid_dataset = glue_convert_examples_to_features(data['validation'], tokenizer, max_length=128, task='sst-2')
train_dataset = train_dataset.shuffle(100).batch(32).repeat(2)
valid_dataset = valid_dataset.batch(64)
test_dataset = glue_convert_examples_to_features(data['test'], tokenizer, max_length=128, task='sst-2')
test_dataset = test_dataset.batch(1)

# Prepare training: Compile tf.keras model with optimizer, loss and learning rate schedule
optimizer = tf.keras.optimizers.Adam(learning_rate=3e-5, epsilon=1e-08, clipnorm=1.0)
loss = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)
metric = tf.keras.metrics.SparseCategoricalAccuracy('accuracy')
model.compile(optimizer=optimizer, loss=loss, metrics=[metric])

model.evaluate(valid_dataset, steps=100)
# Train and evaluate using tf.keras.Model.fit()
# history = model.fit(train_dataset, epochs=2, steps_per_epoch=115,
#                     validation_data=valid_dataset, validation_steps=7)

INFO:absl:Overwrite dataset info from restored data version.
INFO:absl:Reusing dataset glue (/home/dehghani/tensorflow_datasets/glue/sst2/1.0.0)
INFO:absl:Constructing tf.data.Dataset for split None, from /home/dehghani/tensorflow_datasets/glue/sst2/1.0.0


 14/100 [===>..........................] - ETA: 15s - loss: 0.3824 - accuracy: 0.9106WARNING:tensorflow:Your input ran out of data; interrupting training. Make sure that your dataset or generator can generate at least `steps_per_epoch * epochs` batches (in this case, 100 batches). You may need to use the repeat() function when building your dataset.


 14/100 [===>..........................] - ETA: 16s - loss: 0.3605 - accuracy: 0.9106

[0.05353218950331211, 0.9105505]

In [26]:
model.config.output_attentions = True
model.config.output_hidden_states = True

model.distilbert.transformer.output_attentions = True
model.distilbert.transformer.output_hidden_states = True

for layer in model.distilbert.transformer.layer:
    layer.output_attentions = True    
    layer.output_hidden_states = True
    layer.attention.output_attentions = True
    layer.attention.output_hidden_states = True
  
all_examples_grads = []
all_examples_attentions = []
all_examples_x = []
n_examples = 10
for x,y in test_dataset:
    with tf.GradientTape() as tape:
        inputs_embeds = model.distilbert.embeddings(x['input_ids'])
        tape.watch(inputs_embeds)
        logits, hidden_states, attentions = model({'attention_mask':x['attention_mask'], 
                                                    'inputs_embeds':inputs_embeds,
                                                    'token_type_ids': x['token_type_ids']}, training=False
                                            )
        true_logits = logits[:,y[0]]
        print(true_logits)
    grads = tape.gradient(true_logits, inputs_embeds)[0]  
    
    length = tf.reduce_sum(x['attention_mask'], axis=-1)[0]    
    all_examples_grads.append(tf.reduce_sum(grads, -1)[:length])
    
    _attentions = [att.numpy() for att in attentions]
    attentions_mat = np.asarray(_attentions)[:,0]
        
    cropped_input = x['input_ids'][0, :length]
    all_examples_x.append(cropped_input)
    cropped_attention_mat = attentions_mat[:,:,:length,:length]
    all_examples_attentions.append(cropped_attention_mat)
        
    if n_examples == 0:
        break
    n_examples -= 1

tf.Tensor([-3.6605854], shape=(1,), dtype=float32)
tf.Tensor([-3.6501346], shape=(1,), dtype=float32)
tf.Tensor([-3.5526536], shape=(1,), dtype=float32)
tf.Tensor([4.650803], shape=(1,), dtype=float32)
tf.Tensor([-3.1746943], shape=(1,), dtype=float32)
tf.Tensor([-2.030062], shape=(1,), dtype=float32)
tf.Tensor([4.5237985], shape=(1,), dtype=float32)
tf.Tensor([-3.2844446], shape=(1,), dtype=float32)
tf.Tensor([4.5983357], shape=(1,), dtype=float32)
tf.Tensor([-3.4095068], shape=(1,), dtype=float32)
tf.Tensor([2.0042334], shape=(1,), dtype=float32)


In [33]:
print("compute raw relevance scores ...")
all_examples_raw_relevance = {}
for l in np.arange(0,6):
    all_examples_raw_relevance[l] = []
    for i in tqdm(np.arange(len(all_examples_x))):
        tokens = tokens = tokenizer.convert_ids_to_tokens(all_examples_x[i])
        length = len(tokens)
        attention_relevance = get_raw_att_relevance(all_examples_attentions[i], tokens, layer=l)
        all_examples_raw_relevance[l].append(np.asarray(attention_relevance))

print("compute joint relevance scores ...")
all_examples_joint_relevance = {}
for l in np.arange(0,6):
    all_examples_joint_relevance[l] = []
    for i in tqdm(np.arange(len(all_examples_x))):
        tokens = tokenizer.convert_ids_to_tokens(all_examples_x[i])
        length = len(tokens)
        attention_relevance = get_joint_relevance(all_examples_attentions[i], tokens, layer=l)
        all_examples_joint_relevance[l].append(np.asarray(attention_relevance))
    
print("compute flow relevance scores ...")
all_examples_flow_relevance = {}
for l in np.arange(5,6):
    all_examples_flow_relevance[l] = []
    for i in tqdm(np.arange(len(all_examples_x))):
        tokens = tokenizer.convert_ids_to_tokens(all_examples_x[i])
        length = len(tokens)            
        attention_relevance = get_flow_relevance(all_examples_attentions[i], tokens, layer=l)
        all_examples_flow_relevance[l].append(np.asarray(attention_relevance))

  0%|          | 0/11 [00:00<?, ?it/s]

compute raw relevance scores ...
compute joint relevance scores ...


  0%|          | 0/11 [00:00<?, ?it/s]

compute flow relevance scores ...


100%|██████████| 11/11 [07:29<00:00, 40.89s/it]


In [34]:
for l in np.arange(0,6):
    print("###############Layer ",l, "#############")

    print('raw grad')
    print(all_examples_raw_relevance[l][0].shape, all_examples_grads[0].shape)
    raw_sps_grad = []
    for i in np.arange(len(all_examples_x)):
        sp = spearmanr(all_examples_raw_relevance[l][i],all_examples_grads[i])
        raw_sps_grad.append(sp[0])
 
        
    print(np.mean(raw_sps_grad), np.std(raw_sps_grad))

    
    print('joint grad')
    print(all_examples_joint_relevance[l][0].shape, all_examples_grads[0].shape)
    joint_sps_grad = []
    for i in np.arange(len(all_examples_x)):
        sp = spearmanr(all_examples_joint_relevance[l][i],all_examples_grads[i])
        joint_sps_grad.append(sp[0])

        
    print(np.mean(joint_sps_grad), np.std(joint_sps_grad))

  
    print('flow grad')
for l in np.arange(5,6):
    print(all_examples_joint_relevance[l][0].shape, all_examples_grads[0].shape)
    flow_sps_grad = []
    for i in np.arange(len(all_examples_x)):
        sp = spearmanr(all_examples_flow_relevance[l][i],all_examples_grads[i])
        flow_sps_grad.append(sp[0])
        
    print(np.mean(flow_sps_grad), np.std(flow_sps_grad))

###############Layer  0 #############
raw grad
(10,) (10,)
0.11334062720565909 0.19622961505440625
joint grad
(10,) (10,)
0.11334062720565909 0.19622961505440625
flow grad
###############Layer  1 #############
raw grad
(10,) (10,)
0.13438242197187858 0.2093550383622229
joint grad
(10,) (10,)
0.06895459052629656 0.2719340046989568
flow grad
###############Layer  2 #############
raw grad
(10,) (10,)
0.10122507476342474 0.16864664813463295
joint grad
(10,) (10,)
0.10001791316979691 0.2615892774898635
flow grad
###############Layer  3 #############
raw grad
(10,) (10,)
0.03112317207684452 0.2250614444605738
joint grad
(10,) (10,)
0.11786395932036378 0.2698312459821461
flow grad
###############Layer  4 #############
raw grad
(10,) (10,)
0.02943448485732545 0.20305380256410632
joint grad
(10,) (10,)
0.11878310925735795 0.26319519062457825
flow grad
###############Layer  5 #############
raw grad
(10,) (10,)
0.08192566848896693 0.1834930264223889
joint grad
(10,) (10,)
0.11808525406936811 0.25

In [ ]:
np.mean([spearmanr(all_examples_flow_relevance[l][i], all_examples_joint_relevance[l][i]) for i in np.arange(len(all_examples_grads))])
np.mean([spearmanr(all_examples_flow_relevance[l][i], all_examples_grads[i]) for i in np.arange(len(all_examples_grads))])

In [18]:
all_examples_joint_relevance

{5: [array([3.45120337, 0.38171321, 0.35614553, 0.64314935, 0.32497267,
         0.50573498, 0.26461444, 0.29924043, 0.50490437, 3.26832165]),
  array([7.03851756, 0.388758  , 0.46693231, 0.50656893, 0.39827641,
         0.42258721, 0.57095143, 0.5175971 , 0.91077591, 0.53382325,
         0.59075615, 0.59748871, 0.43935374, 0.41571566, 0.37244633,
         0.4351109 , 0.44730335, 0.36060066, 0.43673612, 0.51734508,
         0.37707071, 1.01195414, 0.41534465, 0.37809714, 0.32798143,
         0.34877272, 1.65494549, 7.11818891]),
  array([5.35423478, 0.39700633, 0.3638119 , 0.29394217, 0.50870478,
         0.38152168, 0.36061633, 0.39126104, 0.44283174, 0.44666919,
         0.57516408, 0.42065887, 0.52866337, 0.46851681, 0.47301116,
         0.65925707, 0.35952456, 0.41882319, 1.65683918, 5.49894176]),
  array([5.04530681, 0.36488562, 0.36786416, 0.39413226, 0.36986755,
         0.65043878, 0.3624081 , 0.6024357 , 0.29888739, 0.33457911,
         0.4688398 , 0.42846398, 0.41640085, 0.30

In [29]:

def spearmanr(x, y):
    """ `x`, `y` --> pd.Series"""
    x = pd.Series(x)
    y = pd.Series(y)
    assert x.shape == y.shape
    rx = x.rank(method='dense')
    ry = y.rank(method='dense')
    d = rx - ry
    dsq = np.sum(np.square(d))
    n = x.shape[0]
    coef = 1. - (6. * dsq) / (n * (n**2 - 1.))
    return [coef]

def get_raw_att_relevance(full_att_mat, input_tokens, layer=-1):
    cls_index = 0
    return full_att_mat[layer].sum(axis=0).sum(axis=0)
    

def compute_node_flow(G, labels_to_index, input_nodes, output_nodes,length):
    number_of_nodes = len(labels_to_index)
    flow_values=np.zeros((number_of_nodes,number_of_nodes))
    for key in output_nodes:
        if key not in input_nodes:
            current_layer = int(labels_to_index[key] / length)
            pre_layer = current_layer - 1
            u = labels_to_index[key]
            for inp_node_key in input_nodes:
                v = labels_to_index[inp_node_key]
                flow_value = nx.maximum_flow_value(G,u,v)
                flow_values[u][pre_layer*length+v] = flow_value
            #normalize flow values
            flow_values[u] /= flow_values[u].sum()
            
    return flow_values

def get_flow_relevance(full_att_mat, input_tokens, layer):
    
    res_att_mat = full_att_mat.sum(axis=1)/full_att_mat.shape[1]
    res_att_mat = res_att_mat + np.eye(res_att_mat.shape[1])[None,...]
    res_att_mat = res_att_mat / res_att_mat.sum(axis=-1)[...,None]

    res_adj_mat, res_labels_to_index = get_adjmat(mat=res_att_mat, input_tokens=input_tokens)
    
    A = res_adj_mat
    res_G=nx.from_numpy_matrix(A, create_using=nx.DiGraph())
    for i in np.arange(A.shape[0]):
        for j in np.arange(A.shape[1]):
            nx.set_edge_attributes(res_G, {(i,j): A[i,j]}, 'capacity')

    output_nodes = []
    input_nodes = []
    for key in res_labels_to_index:
        if key.startswith('L'+str(layer+1)+'_'):
            output_nodes.append(key)
        if res_labels_to_index[key] < full_att_mat.shape[-1]:
            input_nodes.append(key)
    
    flow_values = compute_node_flow(res_G, res_labels_to_index, input_nodes, output_nodes, length=full_att_mat.shape[-1])
    
    n_layers = full_att_mat.shape[0]
    length = full_att_mat.shape[-1]
    final_layer_attention_raw = flow_values[(layer+1)*length: (layer+2)*length,layer*length: (layer+1)*length]
    relevance_attention_raw = final_layer_attention_raw.sum(axis=0)

    return relevance_attention_raw
    
    
def get_joint_relevance(full_att_mat, input_tokens, layer):
    att_sum_heads =  full_att_mat.sum(axis=1)/full_att_mat.shape[1]
    joint_attentions = compute_joint_attention(att_sum_heads, add_residual=True)
    relevance_attentions = joint_attentions[layer].sum(axis=0)
    return relevance_attentions


def get_nores_joint_relevance(full_att_mat, input_tokens, layer):
    att_sum_heads =  full_att_mat.sum(axis=1)/full_att_mat.shape[1]
    joint_attentions = compute_joint_attention(att_sum_heads, add_residual=False)
    relevance_attentions = joint_attentions[layer].sum(axis=0)
    return relevance_attentions